import { SportMatch, MetroCity } from './types';

export const INITIAL_MATCHES: SportMatch[] = [
  // Bengaluru
  {
    id: 'bglr-fb-1',
    turfName: 'The Turf Park (HSR Layout)',
    location: 'Sector 2, HSR Layout, Bengaluru',
    city: 'Bengaluru',
    sport: 'Football',
    format: '5v5',
    time: '06:00 PM - 07:00 PM',
    date: '2026-06-14',
    pricePerPlayer: 350,
    slotsTotal: 10,
    slotsFilled: 7,
    joinedPlayers: ['Amit Sharma', 'Rahul Naik', 'Vikram Malhotra', 'Nikhil S.', 'Vijay K.', 'Rohan Roy', 'Siddharth P.'],
    hostName: 'The Turf Park Admins',
    intensity: 'Mixed',
    distance: '1.2 km'
  },
  {
    id: 'bglr-fb-2',
    turfName: 'Dribble Arena (Indiranagar)',
    location: '12th Main Road, Hal 2nd Stage, Indiranagar, Bengaluru',
    city: 'Bengaluru',
    sport: 'Football',
    format: '6v6',
    time: '08:00 PM - 09:00 PM',
    date: '2026-06-14',
    pricePerPlayer: 400,
    slotsTotal: 12,
    slotsFilled: 11,
    joinedPlayers: ['Yash S.', 'Sameer Kumar', 'Pranav R.', 'Aditya Sen', 'Jose M.', 'Tejas V.', 'Kunal B.', 'Deepak N.', 'Srinivas G.', 'Tarun T.', 'Varun P.'],
    hostName: 'Coach Yash',
    intensity: 'Competitive',
    distance: '3.4 km'
  },
  {
    id: 'bglr-cr-1',
    turfName: 'Active Arena (Marathahalli)',
    location: 'Outer Ring Rd, opposite Jeevika Hospital, Bengaluru',
    city: 'Bengaluru',
    sport: 'Box Cricket',
    format: '6v6',
    time: '07:00 PM - 08:30 PM',
    date: '2026-06-14',
    pricePerPlayer: 250,
    slotsTotal: 12,
    slotsFilled: 8,
    joinedPlayers: ['Karthik Pillai', 'Manoj Gowda', 'Suhas R.', 'Bala Vignesh', 'Rupesh Nair', 'Akhil Dev', 'Naveen K.', 'Lokesh L.'],
    hostName: 'Karthik Pillai',
    intensity: 'Friendly',
    distance: '5.8 km'
  },
  {
    id: 'bglr-pd-1',
    turfName: 'Padel House India (Sarjapur)',
    location: 'Silverwood Road, owners court, Sarjapur, Bengaluru',
    city: 'Bengaluru',
    sport: 'Padel',
    format: 'Doubles',
    time: '05:00 PM - 06:00 PM',
    date: '2026-06-15',
    pricePerPlayer: 600,
    slotsTotal: 4,
    slotsFilled: 3,
    joinedPlayers: ['Adnan J.', 'Zayn Malik', 'Sanjay Dutt'],
    hostName: 'Adnan J.',
    intensity: 'Competitive',
    distance: '6.1 km'
  },

  // Delhi NCR
  {
    id: 'del-fb-1',
    turfName: 'Kicksal (Gurugram Sec 56)',
    location: 'Sector 56, Golf Course Road, Gurugram',
    city: 'Delhi NCR',
    sport: 'Football',
    format: '5v5',
    time: '07:00 PM - 08:00 PM',
    date: '2026-06-14',
    pricePerPlayer: 350,
    slotsTotal: 10,
    slotsFilled: 9,
    joinedPlayers: ['Karan Ahluwalia', 'Varun Taneja', 'Dhruv Gupta', 'Anant S.', 'Rohit V.', 'Himanshu D.', 'Abhinav M.', 'Utsav J.', 'Prateek S.'],
    hostName: 'Karan Ahluwalia',
    intensity: 'Competitive',
    distance: '2.5 km'
  },
  {
    id: 'del-pd-1',
    turfName: 'The Grid Padel (South Delhi)',
    location: 'Chanakyapuri, New Delhi',
    city: 'Delhi NCR',
    sport: 'Padel',
    format: 'Doubles',
    time: '04:30 PM - 05:30 PM',
    date: '2026-06-15',
    pricePerPlayer: 700,
    slotsTotal: 4,
    slotsFilled: 2,
    joinedPlayers: ['Rhea Kapoor', 'Kabir Thapar'],
    hostName: 'Rhea Kapoor',
    intensity: 'Friendly',
    distance: '4.7 km'
  },
  {
    id: 'del-cr-1',
    turfName: 'The G.O.A.T Turf (Noida Sec 62)',
    location: 'Block B, Sector 62, Noida, Uttar Pradesh',
    city: 'Delhi NCR',
    sport: 'Box Cricket',
    format: '8v8',
    time: '09:00 PM - 11:00 PM',
    date: '2026-06-14',
    pricePerPlayer: 300,
    slotsTotal: 16,
    slotsFilled: 10,
    joinedPlayers: ['Shubham G.', 'Anubhav P.', 'Mayank S.', 'Aayush M.', 'Devansh K.', 'Sagar R.', 'Sachin B.', 'Ishant D.', 'Rishabh S.', 'Piyush K.'],
    hostName: 'Shubham G.',
    intensity: 'Mixed',
    distance: '9.3 km'
  },

  // Mumbai
  {
    id: 'mum-fb-1',
    turfName: 'The Football Club (TFC Bandra)',
    location: 'Carter Road Promenade, Bandra West, Mumbai',
    city: 'Mumbai',
    sport: 'Football',
    format: '5v5',
    time: '08:00 PM - 09:00 PM',
    date: '2026-06-14',
    pricePerPlayer: 450,
    slotsTotal: 10,
    slotsFilled: 6,
    joinedPlayers: ['Ishaan Mishra', 'Saif Ali', 'Rory Dza', 'Aaditya Deshmukh', 'Ranveer S.', 'Hardik P.'],
    hostName: 'Ishaan Mishra',
    intensity: 'Mixed',
    distance: '0.8 km'
  },
  {
    id: 'mum-pd-1',
    turfName: 'Padel Stars Juhu',
    location: 'Juhu Tara road, Juhu Beach, Mumbai',
    city: 'Mumbai',
    sport: 'Padel',
    format: 'Doubles',
    time: '06:00 PM - 07:00 PM',
    date: '2026-06-14',
    pricePerPlayer: 750,
    slotsTotal: 4,
    slotsFilled: 4,
    joinedPlayers: ['Varun Dhawan', 'Arjun Kapoor', 'Kiara Advani', 'John Abraham'],
    hostName: 'Varun Dhawan',
    intensity: 'Competitive',
    distance: '1.5 km'
  },

  // Hyderabad
  {
    id: 'hyd-fb-1',
    turfName: 'HotFut Gachibowli',
    location: 'Whitefields, Kondapur, Hyderabad',
    city: 'Hyderabad',
    sport: 'Football',
    format: '5v5',
    time: '07:30 PM - 08:30 PM',
    date: '2026-06-14',
    pricePerPlayer: 300,
    slotsTotal: 10,
    slotsFilled: 5,
    joinedPlayers: ['Venkat Reddi', 'Sravan G.', 'Naresh Babu', 'Teja Reddy', 'Chaitanya K.'],
    hostName: 'Venkat Reddi',
    intensity: 'Mixed',
    distance: '2.1 km'
  },
  {
    id: 'hyd-cr-1',
    turfName: 'Velocity Arena (Madhapur)',
    location: 'Image Gardens Road, Madhapur, Hyderabad',
    city: 'Hyderabad',
    sport: 'Box Cricket',
    format: '7v7',
    time: '08:30 PM - 10:00 PM',
    date: '2026-06-15',
    pricePerPlayer: 220,
    slotsTotal: 14,
    slotsFilled: 12,
    joinedPlayers: ['Pranav Tej', 'Abhishek S.', 'Kalyan C.', 'Vishnu V.', 'Vikram R.', 'Sai Krishna', 'Dinesh M.', 'Vijay T.', 'Arun S.', 'Harish K.', 'Mahesh G.', 'Balu P.'],
    hostName: 'Pranav Tej',
    intensity: 'Friendly',
    distance: '1.1 km'
  }
];

export const METRO_CITIES: MetroCity[] = ['Bengaluru', 'Delhi NCR', 'Mumbai', 'Hyderabad', 'Chennai'];
export const SPORT_TYPES = ['Football', 'Box Cricket', 'Padel'] as const;
